# Generated by Django 5.0.3 on 2024-04-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseAdminstration', '0003_alter_content_lesson_alter_lesson_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Percentage of the course completed, from 0 to 100')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.course')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
