# Generated by Django 5.0.3 on 2024-04-11 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lessonID',
        ),
        migrations.RemoveField(
            model_name='section',
            name='sectionID',
        ),
        migrations.AddField(
            model_name='content',
            name='reference',
            field=models.CharField(default='general', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('vid', 'Video'), ('img', 'Image'), ('txt', 'Text'), ('voc', 'Voice')], default='general', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.course'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('choice1', models.CharField(max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(max_length=255)),
                ('choice4', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseAdminstration.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='questiongrade',
            constraint=models.UniqueConstraint(fields=('student', 'quiz'), name='unique_question_grade'),
        ),
        migrations.AddConstraint(
            model_name='selectedchoice',
            constraint=models.UniqueConstraint(fields=('student', 'quiz'), name='unique_selected_choice'),
        ),
    ]
