# Generated by Django 5.0.3 on 2024-04-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0002_remove_content_content_remove_content_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courseAdminstration.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courseAdminstration.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courseAdminstration.course'),
            preserve_default=False,
        ),
    ]
