# Generated by Django 5.0.3 on 2024-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0004_content_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
