# Generated by Django 5.0.3 on 2024-04-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0005_alter_content_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed_students',
            field=models.TextField(default='[]'),
        ),
    ]
