# Generated by Django 5.0.3 on 2024-04-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0006_alter_quiz_lesson'),
        ('courseAdminstration', '0006_lesson_completed_students'),
    ]

    operations = [
    ]
