# Generated by Django 5.0.3 on 2024-05-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0007_merge_20240423_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursePic',
            field=models.ImageField(blank=True, default='course_pics/defaultCourse.jpg', null=True, upload_to='course_pics/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficultyLevel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='week', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='completed_students',
            field=models.JSONField(default=list),
        ),
    ]
