# Generated by Django 5.0.3 on 2024-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseAdminstration', '0008_alter_course_coursepic_alter_course_difficultylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='completed_students',
            field=models.TextField(default=''),
        ),
    ]
